apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wqk6cb8ag-go 
  janus-idp.io/tekton: wqk6cb8ag-go
  backstage.io/kubernetes-id: wqk6cb8ag-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wqk6cb8ag-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml