apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wqk6cb8ag-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wqk6cb8ag-go 
  name: wqk6cb8ag-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wqk6cb8ag-go 
